logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

security:
  jwt:
    token-secret: cGlnZ3ltZXRyaWNzLWphdmEtMjEtc2hhcmVkLXNlY3JldC1rZXktMDEyMzQ1Njc4OTA=
    expiration-seconds: 3600

spring:
  rabbitmq:
    host: rabbitmq
